name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    if: >
      !startsWith(github.event.head_commit.message, 'meta:')
      && !startsWith(github.event.head_commit.message, 'agent:')
      && !startsWith(github.event.head_commit.message, 'tools:')
    runs-on: ubuntu-latest
    steps:
      # Compiling WASM takes a lot of ram
      - name: Increase swapfile
        run: |
          sudo df -h
          sudo swapoff -a
          sudo fallocate -l 50G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Checkout
        uses: actions/checkout@v4

      - name: Git LFS pull
        run: git lfs pull

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build native
        run: bun run build

      - name: Test
        run: bun run test
